### PR TITLE
test: implement test using Kitchen and Inspec, and CI with Travis

### PR DESCRIPTION
**Pull request by daks**
### What type of PR is this?

Implement semantic-release and a limited set of Kitchen/Inspec tests on some platforms.

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [X] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [X] `[docs]`     Documentation changes
- [X] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Documentation checklist

- [X] Updated the `README` (e.g. `Available states`).
- [X] Updated `pillar.example`.

### Testing checklist
- [X] Included in Kitchen (i.e. under `state_top`).
- [X] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [X] Updated the relevant test pillar.

### Additional context

Formula working on a limited set of platforms. First version of semantic-release implementation. Tests pass on working platforms.

### CODE REVIEW

**Comment by daks** [comment]
@myii I added missing files, fixed lint errors, but I'm not sure what to do with the testing matrix, I already took the one from `template-formula`.

**Comment by daks** [comment]
@myii I updated files from `template-formula` and also `FORMULA` to only include Debian and Ubuntu as, for now, those are the only platforms supported. 

Feel free to comment if needed, or merge it, as I think it's OK now.

**Comment by myii** [comment]
@daks I'll have a look at this within the next day.  If there are only minor issues (such as `.travis.yml` needing updating, as it appears it does), then I'll just append a commit and get this merged.

**Comment by myii** [comment]
@daks I've added 2b5e400, would you care to check it before this is merged?

**Comment by myii** [comment]
Thanks for the confirmation on Slack, @daks -- merged.

**Pull request merged**
