### PR TITLE
Feature/declare queues

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**
Replaces 
https://github.com/saltstack/salt/pull/26286

### CODE REVIEW

**Comment by puneetk** [comment]
Does this work and is it backwords compatible. The .install state was added to help users using .latest formula

**Comment by h4ck3rm1k3** [comment]
I am going to create some test cases to prove it works. It passed some simple tests for me, still more to do.

**Comment by puneetk** [comment]
i mean i am thankful for the pull, just want to make sure we don’t affect recent use cases. 
:)

**Comment by h4ck3rm1k3** [comment]
Oh this is totally new functionality that should not affect anyone.

**Comment by puneetk** [comment]
The .install include that u removed is going to be a problem,

**Comment by vr-jack** [comment]
You will want to move your init.sls changes into install.sls. Was hoping the mv in git would handle those instances but apparently not (since I had to recreate an init.sls).

**Comment by h4ck3rm1k3** [comment]
Ok, I moved the changes.

**Comment by vr-jack** [comment]
@h4ck3rm1k3 It's a little more than that. Look at the current master's init.sls. We made a major change this morning and your patch regresses that change.

**Comment by h4ck3rm1k3** [comment]
Ok, I have rebased and squashed and removed all changes from init. thank you for your patience.

**Comment by vr-jack** [comment]
Looks good. No longer should break base. Just to verify intent:

rabbitmq.rabbit-management can be called standalone. It will install the executable and nothing else.

If rabbit-management is installed (by rabbitmq.rabbit-management or other means) the main rabbitmq (or .latest) will configure it.

I personally like that layout. Just wanted to verify that was the intent.

**Comment by h4ck3rm1k3** [comment]
lets see,

rabbitmq.rabbit-management will install the rabbitmqadmin into usr/bin that might want to change to a mapping location eventually. 

Now if the management is installed and the binary is enabled then the other modules will be activated https://github.com/saltstack/salt/pull/26330. If the core changes are available in modules, then you can declared queues, exchanges and bindings. This will use the core changes in to do so .

**Comment by vr-jack** [comment]
@h4ck3rm1k3 One thing you might do is another PR for updating the README.rst with the new rabbitmq.rabbit-management option and mentioning the earliest version it will work with. The module check should properly fail if rabbitmqadmin isn't installed as well as if the module isn't there, so there shouldn't be any feature issues. Excellent work. Sorry I caused you issues with my PR.

**Comment by h4ck3rm1k3** [comment]
Thanks so much. I will update the readme as soon as the core patch gets resolved.

**Pull request merged**
