### PR TITLE
Integrate map.jinja

### PR DESCRIPTION
**Pull request by daks**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [X] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [X] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

* Refactoring map.jinja with latest standards from template-formula
* use it to manage installed packages

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [X] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

Only Debian 10 tests are enabled. Work is needed to re-enable others.

I plan to continue the work on map.jinja in a furthur PR to extend its use in states.

I wonder if libsaltcli.jinja and libtofs.jinja files needs to be added too, or it has no utility if they are not completely integrated.

### CODE REVIEW

**Comment by myii** [comment]
@daks Thanks for this PR.  My standard method for these `map.jinja` refactorisation PRs is to get the `map.jinja` verifier in place first, to confirm we've got the same before and after.  I used to do this locally but now we've got it up and running, I'll provide it for this formula so that this PR can be automatically verified.

**Comment by myii** [comment]
I'm just waiting to finalise https://github.com/saltstack-formulas/openvpn-formula/pull/132 -- held up by upgrading the matrix to include `fedora-33` and `arch-py3` (first is available, second is almost done).

**Comment by daks** [comment]
@myii any news about this PR, can it be merged?

**Comment by myii** [comment]
@daks Finally had a chance to review this, at least generally.  The changes look good to me, I compared them with the new `map.jinja` verifier as well (in my fork).  I do have one issue, though: `test/integration/default/controls/repo.rb` is too restrictive and only allows us to use one instance for testing (`latest-debian-10-master-py3`):

* https://gitlab.com/myii/rabbitmq-formula/-/pipelines/233097816
* https://travis-ci.com/github/saltstack-formulas/rabbitmq-formula/builds/194354522

The last successful `master` branch build in Travis had 6 instances being tested across Debian and Ubuntu:

* https://travis-ci.com/github/saltstack-formulas/rabbitmq-formula/builds/168336901

I also tried without `test/integration/default/controls/repo.rb` and 6 instances pass:

* https://gitlab.com/myii/rabbitmq-formula/-/pipelines/233293345

We're already restricted to Debian and Ubuntu, when this formula suggests it should work for other platforms as well.  Let's at least try to keep these 6 instances working, even if we have to use a simplified version of `test/integration/default/controls/repo.rb` for the time being.

Thanks for your patience!

**Comment by myii** [comment]
@daks I've merged #63, which is my initial work on the `map.jinja` verifier.  When you rebase this, you're going to need the updated verification files, which I can provide -- please ensure that "Allow edits and access to secrets by maintainers" is selected, so that I can push them on top to get the tests working.

**Comment by noelmcloughlin** [comment]
Covered by #66

**Pull request closed without merging**
