### PR TITLE
Management of env file

### PR DESCRIPTION
**Pull request by daks**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

### What type of PR is this?

This PR adds support to manage a file to provide to RabbitMQ environment variables. Those are mandatory to change some core settings, like the DB location. See https://www.rabbitmq.com/relocate.html and https://www.rabbitmq.com/configure.html

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [X] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [X] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

In  `config.sls` I added the management of `/etc/rabbitmq/rabbitmq-env.conf` file. It can be populated using pillar `rabbitmq:env`.

### Pillar / config required to test the proposed changes

Please see `pillar.example`.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [X] Updated `pillar.example`.

### Testing checklist

- [X] Included in Kitchen (i.e. under `state_top`).
- [X] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [X] Updated the relevant test pillar.

### CODE REVIEW

**Comment by daks** [comment]
I may add some inspec tests once #57 is merged

**Comment by daks** [comment]
Needs some rebase, consider WIP for now.

**Comment by daks** [comment]
ready for review

**Comment by myii** [comment]
@daks These changes look fine but would you mind using the following version of `kitchen.yml`?

* https://github.com/myii/rabbitmq-formula/blob/58_0/kitchen.yml

All working well with it:

* https://travis-ci.org/myii/rabbitmq-formula/builds/628720868

This allows me to keep using the single template `kitchen.yml` across all formulas via. the `ssf-formula`.  It is a bit more duplication but it's for the wider benefit for maintaining changes across formulas.

**Comment by daks** [comment]
you mean move the `dependencies` part in each `suite` section? It feels redundant but if it eases maintenance with `ssf-formula`, I'll change it.

**Comment by myii** [comment]
> you mean move the `dependencies` part in each `suite` section? It feels redundant but if it eases maintenance with `ssf-formula`, I'll change it.

@daks Yes, it is redundant but it was the easiest way to ensure consistency of output from the `ssf-formula`.  I'm sure it could eventually be improved to collect shared items into the uppermost level but that will take time and testing.

**Comment by daks** [comment]
done

**Comment by myii** [comment]
@daks Not quite, they don't have the correct indentation level.  It would be easier to take the file from my branch and use that.  Then there won't be any discrepancies.

**Comment by myii** [comment]
The issue is that `kitchen.yml` has essentially become a "managed" file via. `ssf-formula`.

**Comment by myii** [comment]
@daks Thanks, I've merged the PR.  Since the `ssf-formula` doesn't currently handle comments for the `dependencies` section, I'll remove those in a `[skip ci]` commit, so that this doesn't cause issues further down the line when propagating changes to this formula's `kitchen.yml` file.

**Comment by daks** [comment]
okay, I think those comments can be useful (even if maybe not well expressed) to understand what the dependencies are for

**Comment by daks** [comment]
thanks for the merge

**Comment by myii** [comment]
@daks Of course, things are not ideal but then managed 60+ formulas is going to result in some compromises.  These features could be integrated into the `ssf-formula` eventually.

**Comment by myii** [comment]
BTW, we already have an example of exactly the same thing in the [`cert-formula`](https://github.com/saltstack-formulas/cert-formula/blob/bbcc4d7f5bbe0d0fc55852bf177cb3b999d5a0cb/kitchen.yml#L193-L197).

**Pull request merged**
