### PR TITLE
chore(clean): remove os provided erlang package too

### LINKED ISSUE #116: [BUG] erlang package conflict between os and upstream repo
### Formula commit hash / release tag

Master

### Versions reports (master & minion)

```
# salt --versions-report
Salt Version:
           Salt: 3001.8
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.12.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```

### Pillar / config used

---

### Describe the bug

Installing RabbitMQ fails if OS-provided erlang package conflicts with Upstream-Repo Erlang package. See attached log

```  file /usr/lib64/erlang/bin/epmd from install of erlang-erts-R16B-03.18.el7.x86_64 conflicts with file from package erlang-23.3.4.6-1.el7.x86_64```

### Expected behaviour

no package conflict

### Additional context

[rabbitmq_error.txt](https://github.com/saltstack-formulas/rabbitmq-formula/files/7136634/rabbitmq_error.txt)

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

#116

### Describe the changes you're proposing

Removes `erlang` package as part of clean state to fix #116 that way.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
Selfie merging as open a long time. CI passed

**Comment by daks** [comment]
@noelmcloughlin does this PR means that before erland package was installed, and that now it's not?

**Comment by noelmcloughlin** [comment]
@daks  No. In the PR description it says following text with no indication packages are installed or not. Its  a clean state. 

"_Removes erlang package as part of clean state to fix https://github.com/saltstack-formulas/rabbitmq-formula/issues/116 that way._"

**Comment by daks** [comment]
ok got it :+1:

**Pull request merged**
