### PR TITLE
Fix for issue where users were created before a VH they should have p…

### PR DESCRIPTION
**Pull request by jaygorrell**
…ermissions on; removed deprecated VH parameters

I believe this also takes care of #34

### CODE REVIEW

**Comment by envintus** [comment]
The vhost declaration in your commit failed for me. This is what needed to be done for pillar data to work correctly when adding vhosts.

~~~
rabbitmq:
  vhost:
    my_vhost:
      - name: '/my-vhost
~~~

**Comment by jaygorrell** [comment]
Interesting. Did you pull down the config.sls as well? It's more than just a re-ordering the states -- the 'key' is only used to name the state uniquely, then the value is used for the actual vhost name. Passing in a list would only work with the previous for loop in the state, which I've removed here.

To be fair though, I should have put the VH value on the same line as the name... I'll add that now with a squash.

**Comment by envintus** [comment]
Ah ok, you know what I just reordered the states locally, because I thought that’s all it was. Sorry about that. Thanks for the quick response. Hopefully your pull request gets approved.

**Comment by jaygorrell** [comment]
No problem, thanks for the comments!

**Comment by multani** [comment]
I also tested, and it works OK! Very appreciated change, both for the simpler pillar definitions and for removing the warnings from #34

**Comment by gravyboat** [comment]
Thanks.

**Comment by syphernl** [comment]
@jaygorrell This seems to have broken the ability to create multiple vhosts at once.
In our current version (before upgrading) we had the following (partial) pillar:
```yaml
rabbitmq:
  vhost:
    demo1:
      - owner: masteruser
    demo2:
      - owner: masteruser
    demo3:
      - owner: masteruser
```

This doesn't seem possible since this change. Any pointers in how to achieve this?

**Comment by jaygorrell** [comment]
@syphernl I wrote this over 9 months ago so forgive me if this is a bit blurry at this point :)

Did you try something like this?
```
rabbitmq:
  vhost:
    - vh_1: demo1
    - vh_2: demo2
    - vh_3: demo3
```

The owner should be defined from the user side, though. Per [this page],(https://docs.saltstack.com/en/latest/ref/states/all/salt.states.rabbitmq_vhost.html) `owner` has been deprecated since v2015.8.0.

**Comment by syphernl** [comment]
@jaygorrell No, this results in the highstate breaking completely:
```
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'local': ["Rendering SLS 'dev:rabbitmq.config' failed: Jinja variable 'list object' has no attribute 'items'"]}
```

**Comment by jaygorrell** [comment]
Oops, you're right. That should have been a list. Sorry about that.

**Pull request merged**
