### PR TITLE
fix(): Pass proper args to the rabbitmq user state

### PR DESCRIPTION
**Pull request by dahrens**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

Restores the behavior changed by 346df024

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

Without this patch the state is rendered like that:

```
rabbitmq-config-user-present-{{ name }}:
  rabbitmq_user.present:
    - name: {{ name }}
    -
      - password: foo
      - tags: ['administrator']
    - require: [...]
```

Which leads to creation, but without e.g. the tags being applied.
This looks a little awkward in YAML, but was revealed when asking salt to render: `salt-call state.show_sls rabbitmq`.

### CODE REVIEW

**Comment by myii** [comment]
> Force pushing the feature branch to adjust the commit message to pass the commitlint check did not trigger the checks again. Can anyone trigger them manually or should I create a new PR?

@dahrens Don't worry, the GitLab CI will still run without intervention.  Your commit message still needs some adjustment to be accepted by commitlint:

```diff
-fix(user): Pass proper args to the rabbitmq state.
+fix(user): pass proper args to the rabbitmq state
```

**Comment by noelmcloughlin** [comment]
@dahrens looks good and could be merged once commit messages are fixed.  This change is also included in #75

**Comment by myii** [comment]
@dahrens Unfortunately, that needs to be lowercase `pass` instead of `Pass`.

**Comment by dahrens** [comment]
> @dahrens Unfortunately, that needs to be lowercase `pass` instead of `Pass`.

I'm currently installing commitlint to get out of this trap... :upside_down_face:

**Comment by myii** [comment]
@dahrens We have `pre-commit` configured for this repo, so you could use that instead, to perform all the linting:

* https://github.com/saltstack-formulas/rabbitmq-formula#pre-commit

**Review by noelmcloughlin — APPROVED** [review]

**Pull request merged**
