### PR TITLE
fix(latest.sls): use Bintray repo on Debian

### PR DESCRIPTION
**Pull request by sylvainfaivre**
The rabbitmq.com debian repo is outdated (no update since January 2018)
The Bintray repo provides Erlang and RabbitMQ packages, see https://www.rabbitmq.com/install-debian.html

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

None

### Describe the changes you're proposing

Use Bintray repo instead of outdated rabbitmq.com repo

### Pillar / config required to test the proposed changes

None

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
Thanks for this PR, @sylvainfaivre.  Just an initial suggestion about the commit message.

https://travis-ci.com/saltstack-formulas/rabbitmq-formula/jobs/256187697#L346-L350

```sls
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

So perhaps it can be changed to:

```diff
-Use Bintray repo on Debian
+fix(latest.sls): use Bintray repo on Debian
```

**Comment by myii** [comment]
Another problem we have here (unrelated to this PR) is that the `rabbitmq.latest` state isn't being run in the CI.  So this PR isn't being tested so far.  Perhaps it would be worth merging a PR for that first, so that this PR can benefit from that as well.

**Comment by myii** [comment]
Tested adding a `latest` suite, before and after this PR:

* https://travis-ci.org/myii/rabbitmq-formula/builds/611473664 (before)
* https://travis-ci.org/myii/rabbitmq-formula/builds/611488940 (after)

We can skip around the common failures for the time being.  This PR looks like it is appropriate.

**Comment by sylvainfaivre** [comment]
OK I edited the commit title, do you want to merge your changes to the tests before merging this PR ? Anything else ?

**Comment by myii** [comment]
> OK I edited the commit title, do you want to merge your changes to the tests before merging this PR ? Anything else ?

@sylvainfaivre Thanks for making the change.  Unfortunately, need a slight adjustment to pass the `commitlint`, so that this makes a new release with `semantic-release` (see the [commit message formatting](https://github.com/saltstack-formulas/.github/blob/master/CONTRIBUTING.rst#commit-message-formatting) section of `CONTRIBUTING` for more details):

```diff
-fix(latest.sls): Use Bintray repo on Debian
+fix(latest.sls): use Bintray repo on Debian
```

Otherwise, this looks good to go.

**Comment by myii** [comment]
@sylvainfaivre It's OK, I've made the change during the merge process, so the release should be created as usual.  Also noticed this is your first ever contribution -- welcome to GitHub!

Thanks for the review, @daks.

**Pull request merged**
